spring:
  datasource:
    url: jdbc:h2:mem:${DB_NAME:capitole}
    driverClassName: org.h2.Driver
    username: ${DB_USER:adminUser}
    password: ${DB_PASS:C@pitol3}

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console.enabled: true

  flyway:
    user: ${DB_USER:adminUser}
    password: ${DB_PASS:C@pitol3}
    schemas: ${DB_NAME:capitole}
    url: jdbc:h2:mem:${DB_NAME:capitole}
    locations: classpath:db/migration
    baseline-on-migrate: true
