spring:
  datasource:
    url: jdbc:h2:mem:capitole
    driverClassName: org.h2.Driver
    username: adminUser
    password: C@pitol3

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console.enabled: true

  flyway:
    user: adminUser
    password: C@pitol3
    schemas: capitole
    url: jdbc:h2:mem:capitole
    locations: classpath:db/migration
    baseline-on-migrate: true
