INSERT INTO  PRICES_LIST (`NAME`) VALUES ('PL001');
INSERT INTO  PRICES_LIST (`NAME`) VALUES ('PL002');
INSERT INTO  PRICES_LIST (`NAME`) VALUES ('PL003');
INSERT INTO  PRICES_LIST (`NAME`) VALUES ('PL004');