INSERT INTO  PRICES_LIST (`PRICE`) VALUES (33.00);
INSERT INTO  PRICES_LIST (`PRICE`) VALUES (23.00);
INSERT INTO  PRICES_LIST (`PRICE`) VALUES (33.00);
INSERT INTO  PRICES_LIST (`PRICE`) VALUES (35.00);
-- Commit the transaction
COMMIT;